crystal:
  num_axes: 1             # number of individual optical axes, 1 -> isotropic, 2 -> uniaxial, 3 -> biaxial
  name: "YbKYF"           # name of crystal
  T: 300                  # temperature [K]
  index_1: 1.45           # first refractive index, no
  index_2:                # second refractive index ne
  index_3:                # refractive index for E||c (or E||Z) (only used for biaxial crystal)
  doping_level: 10.0      # doping level [%]
  cation_density: 1.4e22  # cation density of host [cm^-3]
  baxis:                  # vector specifying b(or Y)-axis (only used for biaxial crystal)
  caxis: [1.0, 0.0, 0.0]  # vector specifying c(or Z)-axis (not used for isotropic crystal)
  shape: "cuboid"         # "cuboid" or "brewster"
  W: 2.5                  # width (along x)
  H: 2.5                  # height (along y)
  L: 7.5                  # length (along z)
  QE: 1.0                 # internal quantum efficiency
  alpha_b: 0.0            # background absorption coefficient

beam:
  distribution: "gauss"   # valid inputs: "gauss", "tophat"
  wl: 1020.0              # excitation wavelength
  k: [0.0, 0.0, 1.0]      # vector specifying the beam direction
  d: 0.5                  # beam diameter
  p0: [1.25, 1.25, 0.0]   # point where the beam passes
  E: [1.0, 0.0, 0.0]      # polarization

simulation:
  N: 1e3                  # number of simulated fluorescence rays
  step: 0.5               # step size in ray tracing [mm]
  max_ref_count: 0        # max reflection counts to stop ray tracing (0 => infinity)
  pump_depletion: true    # false => no pump depletion (uniform excitation), true => pump delete (Beer-Lambert law)
